version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      JWT_SECRET: =====================MicrologSecretJWT=====================
    links:
      - postgres

volumes:
  postgres-data:
